urls:
  coinMarketCap: 'https://api.coinmarketcap.com'
  coingecko: 'https://api.coingecko.com'
  spectrum: 'https://api.spectrum.fi'
  dexHunter: 'https://api-us.dexhunterv3.app'
  ergoExplorer: 'https://api.ergoplatform.com'
  cardanoKoios: 'https://api.koios.rest/api/v1'
  bitcoinEsplora: 'https://mempool.space'
  dogeBlockcypher: 'https://api.blockcypher.com'
  ethereumRpc: 'https://eth-mainnet.public.blastapi.io'
  binanceRpc: 'https://bsc-mainnet.public.blastapi.io'
  minswap: 'https://monorepo-mainnet-prod.minswap.org/graphql'
auth:
  koios: ''
minimumFee:
  NFT: '1ce1ea41ceaed94a6976a047645ffb3f3da3916685268c8f2d8f80f892147caa'
  minimumFeeAddress: '9fmj8dX6QFy9PS2zCqYJj4LTyDvWRS29BBuSTToy961oWf2VaQQ'
  feeAddress: '9gPqDuyxpmV2bR62zdbgxuvJAahDUpnaZw8Srv2JYHauAiHZEb4'
  minBoxErg: '200000'
  fetchBoxRetry: 3
  rsnRatioPrecision: 6
  bitcoinTxVSize: 150
  bitcoinMinUtxo: 0.00000546
  dogeTxSize: 226
  bitcoinRunesTxVSize: 383 # 3 NS inputs -> 3 NS, 1 OP_RETURN of size 23 and 1 Taproot outputs
  dogeMinUtxo: 0.01
  ethereumAvgGasPricePeriod: 7200 # blocks (1 day long)
  ethereumNetworkFeeMultiplier: 1.5
  binanceTxFee: 0.00002
  defaultFee:
    delays:
      ergo: 5
      cardano: 30
      bitcoin: 2
      doge: 10
      ethereum: 50
      binance: 200
    bridgeFeeUSD: 10
    ergNetworkFee: 0.0013
    adaNetworkFee: 3.4
    feeRatioFloat: 0.005
    bitcoinConfirmation: 6
    dogeConfirmation: 10
  supportedTokens:
    - tokenId: ''
      priceBackend: ''
      priceBackendParams: # depends on priceBackend
        network: ''
      fee: # will use defaultFee if this is not provided
        delays:
          ergo: 5
          cardano: 30
          bitcoin: 2
          doge: 10
          ethereum: 50
          binance: 200
        bridgeFeeUSD: 10
        ergNetworkFee: 0.0013
        adaNetworkFee: 3.4
        feeRatioFloat: 0.005
        bitcoinConfirmation: 6
tokensPath: './config/tokens.json' # path to supported tokens of bridge 
logs:
  - type: 'file'
    path: './logs/'
    maxSize: '20m'
    maxFiles: '14d'
    level: 'debug'
  - type: 'console'
    level: 'info'
triggerPercent:
  bridgeFee: 10
  rsnRatio: 10
  networkFee:
    cardano: 10
    ergo: 10
    bitcoin: 100
    ethereum: 200
    binance: 10
    doge: 100
    bitcoin-runes: 100
discordWebHookUrl: '' # Discord webhook url for sending notifications
interval: 14400 # every 4 hours
kv:
  restApiUrl: # Upstash URL
  restApiToken: # Upstash token
database:
  type: 'sqlite' # options: postgres, sqlite
  path: './sqlite/minFeeJob.sqlite' # database path (for sqlite)
  # host: '' # database host (for postgres)
  # port: 5432 # database port (for postgres)
  # ssl: false # use ssl for database (for postgres)
  # user: '' # database user (for postgres)
  # password: '' # database password (for postgres)
  # name: '' # database name (for postgres)
